LinuxCommandPractice
hosoya-yuji/LinuxCommandPractice pull request #1
Opened 2024-03-28 17:18 UTC by hosoya-yuji

# LinuxCommandPractice
LinuxCommandPracticeの実施

# LinuxCommandPractice
コマンドからファイル、フォルダの作成、削除を実施。

# つまづいた点
プルリクエストが表示されなかった
原因：ブランチを一つしか作成しておらず比較対象がなかったため
解決：ブランチを作成してanswer.shを更新してリモートリポジトリに追加後ブルリクエストが表示されました。

3/29
main、main-2両方でpushしていました。
Geekationオリエンテーションを確認したところ片方のブランチでしかpushを行っていなかったので
そちらを参考にmain-2のみpushを行いPRしました。

2024-03-29 03:21 UTC, y0sh1ka2u requested changes
コメントしている箇所以外ももう一度コマンドを確認してみてください。

2024-03-29 03:21 UTC, y0sh1ka2u commented on answer.sh
> +$ ls
`ls`だけでは`.git`は表示できないのでご確認お願いします！

2024-03-29 03:21 UTC, y0sh1ka2u commented on answer.sh
> +$ mkdir ./practice_dir_1 practice_dir_2
このコマンドだと、`practice_dir_1`と`practice_dir_2`の二つのディレクトリを作ろうとしているのでご確認お願いいたします！

2024-03-30 02:15 UTC, hosoya-yuji commented on answer.sh
> +$ ls
以下に修正しました。
ls → ls -a

2024-03-30 02:15 UTC, hosoya-yuji commented on answer.sh
> +$ mkdir ./practice_dir_1 practice_dir_2
以下に修正しました。
$ mkdir ./practice_dir_1 practice_dir_2 → $ mkdir ./practice_dir_1/practice_dir_2

2024-04-01 02:23 UTC, y0sh1ka2u approved these changes
LGTM!

2024-04-08 15:31 UTC, merged